### ISSUE TITLE
Cannot initialize object if there is a space between colon and first value member

### ISSUE THREAD

**Issue by jleeothon** [Seldomberry/Cortex#134]
Tried this in the shell:
```
:: $ iterator myit: null, null
typedef::construct: typedef '::myit' points to nothing1:1: error: define of variable '::myit' of type '::cortex::lang::iterator' failed
:: $ iterator myit:null, null
```

The second try worked.

**Comment by SanderMertens** [comment]
The reason behind this issue is not the space, but is a bit more subtle. The iterator type doesn't initialize correctly yet, which causes the `real` member of the typedef class to point to `null`.

I'm guessing that when in the initializer of an iterator, you do:
```
return cx_type__init(cx_type(object));
```
the statement should work.

Note the extra `_` in `cx_type__init`. The reason for this is to prevent a name clash between the delegate and the callback. This is an issue that will be solved with #12.

**Comment by jleeothon** [comment]
Sorry... that worked. Last time when we went over it, we did a quick return 0.

**Comment by SanderMertens** [comment]
It is idiomatic to always call the initializer / constructor / destructor of the base class. I may have forgot to mention that :-)

**Comment by jleeothon** [comment]
Talk about that, I'd like that we spec'd the logging framework (that's what I call it, but I don't know how you call it). It could be important to make it multipurpose, easily integratable with e.g. our current test framework under construction.

I'll comment on this in another ticket.
